import os

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
LOG_FILE = os.path.join(BASE_DIR, "trades.json")

BOT_TOKEN = "8747551982:AAGlQW_Cll2xtV21e2gAo1bI-CnEqxf2vOI"
CHAT_ID = "5909464423"

HOLIDAYS_2026 = [
    "2026-01-26",  # Republic Day
    "2026-03-03",  # Holi
    "2026-03-26",  # Shri Ram Navami
    "2026-03-31",  # Mahavir Jayanti
    "2026-04-03",  # Good Friday
    "2026-04-14",  # Ambedkar Jayanti
    "2026-05-01",  # Maharashtra Day
    "2026-05-28",  # Bakri Eid
    "2026-06-26",  # Moharram
    "2026-09-14",  # Ganesh Chaturthi
    "2026-10-02",  # Gandhi Jayanti
    "2026-10-20",  # Dussehra
    "2026-11-10",  # Diwali Balipratipada
]

GREEN = "\033[92m"
RED = "\033[91m"
RESET = "\033[0m"

stocks = [
    "RELIANCE.NS","TCS.NS","HDFCBANK.NS","INFY.NS","ICICIBANK.NS",
    "HINDUNILVR.NS","ITC.NS","SBIN.NS","BHARTIARTL.NS","KOTAKBANK.NS",
    "LT.NS","AXISBANK.NS","ASIANPAINT.NS","MARUTI.NS","SUNPHARMA.NS",
    "TITAN.NS","ULTRACEMCO.NS","NESTLEIND.NS","POWERGRID.NS","NTPC.NS",
    "BAJFINANCE.NS","BAJAJFINSV.NS","HCLTECH.NS","WIPRO.NS","TECHM.NS",
    "ADANIENT.NS","ADANIPORTS.NS","JSWSTEEL.NS","TATASTEEL.NS","GRASIM.NS",
    "DRREDDY.NS","CIPLA.NS","DIVISLAB.NS","EICHERMOT.NS","HEROMOTOCO.NS",
    "ONGC.NS","COALINDIA.NS","BPCL.NS","INDUSINDBK.NS","BRITANNIA.NS",
    "APOLLOHOSP.NS","BAJAJ-AUTO.NS","HDFCLIFE.NS","SBILIFE.NS","ICICIPRULI.NS",
    "DABUR.NS","GODREJCP.NS","PIDILITIND.NS","TATACONSUM.NS","M&M.NS","UPL.NS","SHREECEM.NS","AMBUJACEM.NS",
    "ACC.NS","VEDL.NS","SIEMENS.NS","ABB.NS","BHEL.NS",
    "HAL.NS","BEL.NS","GAIL.NS","IOC.NS","TORNTPHARM.NS",
    "LUPIN.NS","AUROPHARMA.NS","ICICIGI.NS","HAVELLS.NS","VOLTAS.NS",
    "COLPAL.NS","MARICO.NS","BERGEPAINT.NS","SRF.NS",
    "MPHASIS.NS","NAUKRI.NS","PAYTM.NS",
    "POLYCAB.NS","INDIGO.NS","DLF.NS","OBEROIRLTY.NS",
    "PNB.NS","BANKBARODA.NS","CANBK.NS","UNIONBANK.NS",
    "IDFCFIRSTB.NS","FEDERALBNK.NS","RBLBANK.NS"
]
